api/src/main/java/org/openmrs/module/appointments/constants/PrivilegeConstants.java
api/src/main/java/org/openmrs/module/appointments/model/Appointment.java
api/src/main/java/org/openmrs/module/appointments/service/AppointmentsService.java
api/src/main/java/org/openmrs/module/appointments/service/impl/AppointmentsServiceImpl.java
api/src/main/resources/addPrivilegesToManageSelfAppointmentsRole.sql
api/src/main/resources/liquibase.xml
api/src/test/java/org/openmrs/module/appointments/service/AppointmentsServiceTest.java
api/src/test/java/org/openmrs/module/appointments/service/impl/AppointmentsServiceImplTest.java
api/src/test/resources/userRolesandPrivileges.xml

https://bahmni.atlassian.net/browse/BAH-625?jql=

BAH-625 Add self privilege pr

---

api/src/main/java/org/openmrs/module/appointments/dao/impl/AppointmentDaoImpl.java
api/src/main/java/org/openmrs/module/appointments/model/AppointmentSearchRequest.java
api/src/main/java/org/openmrs/module/appointments/service/impl/AppointmentsServiceImpl.java
api/src/test/java/org/openmrs/module/appointments/dao/impl/AppointmentDaoImplIT.java
api/src/test/java/org/openmrs/module/appointments/service/impl/AppointmentsServiceImplTest.java
api/src/test/resources/appointmentTestData.xml
omod/src/main/java/org/openmrs/module/appointments/web/validators/AppointmentSearchValidator.java
omod/src/test/java/org/openmrs/module/appointments/web/controller/AppointmentsControllerIT.java
omod/src/test/java/org/openmrs/module/appointments/web/validators/AppointmentSearchRequestValidatorTest.java

Enhanced search patient endpoint .
[Link to card](https://bahmni.atlassian.net/browse/BAH-933)

BAH-933: Enhanced search patient endpoint to take patient UUID and limit

---

api/src/main/java/org/openmrs/module/appointments/constants/PrivilegeConstants.java
api/src/main/java/org/openmrs/module/appointments/service/AppointmentServiceDefinitionService.java
api/src/main/java/org/openmrs/module/appointments/service/AppointmentsService.java

Jira Card : https://bahmni.atlassian.net/browse/AP-29

Dubey,Sukreet | AP-29 | Fix privileges for Services

---

omod/src/main/java/org/openmrs/module/appointments/web/controller/AppointmentController.java
omod/src/main/java/org/openmrs/module/appointments/web/controller/AppointmentServiceController.java
omod/src/main/java/org/openmrs/module/appointments/web/controller/AppointmentServicesController.java
omod/src/main/java/org/openmrs/module/appointments/web/controller/AppointmentsController.java
omod/src/main/java/org/openmrs/module/appointments/web/controller/RecurringAppointmentsController.java
omod/src/main/java/org/openmrs/module/appointments/web/controller/SpecialityController.java
omod/src/test/java/org/openmrs/module/appointments/web/controller/AppointmentControllerIT.java
omod/src/test/java/org/openmrs/module/appointments/web/controller/AppointmentControllerTest.java
omod/src/test/java/org/openmrs/module/appointments/web/controller/AppointmentsControllerIT.java
omod/src/test/java/org/openmrs/module/appointments/web/controller/AppointmentsControllerTest.java

[BAH-966](https://bahmni.atlassian.net/browse/BAH-966)

BAH-966 | Api authentication across tabs

---

omod/pom.xml
pom.xml

BAH 1033 - Adding pom.xml changes to add Appointments 1.2 to sonatype

---

api/pom.xml
omod/pom.xml
pom.xml

Change release verison and add relsese repository for nexus

---

api/pom.xml
api/src/main/java/org/openmrs/module/appointments/AppointmentsActivator.java
omod/pom.xml
pom.xml

Fix nexus validations;Upgrade version to 1.3.0-SNAPSHOT

---

api/src/main/java/org/openmrs/module/appointments/service/impl/AppointmentRecurringPatternServiceImpl.java
api/src/main/java/org/openmrs/module/appointments/service/impl/AppointmentsServiceImpl.java
api/src/test/java/org/openmrs/module/appointments/service/impl/AppointmentRecurringPatternServiceImplTest.java
omod/src/main/java/org/openmrs/module/appointments/web/service/impl/AllAppointmentRecurringPatternUpdateService.java
omod/src/test/java/org/openmrs/module/appointments/web/controller/AppointmentControllerIT.java
omod/src/test/java/org/openmrs/module/appointments/web/controller/RecurringAppointmentsControllerIT.java
omod/src/test/java/org/openmrs/module/appointments/web/service/impl/AllAppointmentRecurringPatternUpdateServiceTest.java
omod/src/test/resources/appointmentTestData.xml

This PR handles reurring appointment update/cancel scenarios which were missed for Appointment Request.
Issue Link: https://bahmni.atlassian.net/browse/AP-63

AP-63 | Fix recurring appointment scenarios for Appointment Request

---

api/src/main/java/org/openmrs/module/appointments/conflicts/impl/PatientDoubleBookingConflict.java
api/src/test/java/org/openmrs/module/appointments/conflicts/impl/PatientDoubleBookingConflictTest.java

Link to card :  https://bahmni.atlassian.net/browse/AP-64

AP-64 | Sukreet | Ignore cancelled appointments for determining conflicts.

---

.github/workflows/validate_pr.yml
README.md
api/src/test/java/org/openmrs/module/appointments/util/DateUtilTest.java
omod/src/test/java/org/openmrs/module/appointments/web/service/impl/AllAppointmentRecurringPatternUpdateServiceTest.java
omod/src/test/java/org/openmrs/module/appointments/web/service/impl/WeeklyRecurringAppointmentsGenerationServiceTest.java

https://bahmni.atlassian.net/browse/BAH-1133

BAH-1133: Setting up time zone sensitive tests, adjusting GitHub Actions.

---

api/src/main/resources/patientPastAppointments.sql
api/src/main/resources/patientUpcomingAppointments.sql

https://bahmni.atlassian.net/browse/BAH-1136

Bindu | BAH-1136 | Change query to get provider from patient appointment provider table

---

api/src/main/resources/liquibase.xml

https://bahmni.atlassian.net/browse/BAH-1136

Bindu | BAH-1136 | change the changeset id to fix liquibase migration failure issue

---

api/src/main/java/org/openmrs/module/appointments/model/Appointment.java
api/src/main/java/org/openmrs/module/appointments/notification/impl/DefaultTCAppointmentPatientEmailNotifier.java
api/src/main/java/org/openmrs/module/appointments/service/impl/AppointmentsServiceImpl.java
api/src/main/resources/Appointment.hbm.xml
api/src/main/resources/liquibase.xml
api/src/main/resources/patientUpcomingAppointments_v2.sql
api/src/test/java/org/openmrs/module/appointments/service/impl/AppointmentsServiceImplTest.java
omod/src/main/java/org/openmrs/module/appointments/web/contract/AppointmentRequest.java
omod/src/main/java/org/openmrs/module/appointments/web/mapper/AppointmentMapper.java
omod/src/main/java/org/openmrs/module/appointments/web/service/AbstractRecurringAppointmentsService.java
omod/src/main/java/org/openmrs/module/appointments/web/service/impl/DailyRecurringAppointmentsGenerationService.java

Changing detection logic of Virtual/Teleconsultation
Also removing class level variable which can error in race condition in DailyRecurringAppointmentsGenerationService.java

BAH-1225 | Removing appointment.teleconsultation attribute.

---

pom.xml

This PR is about:
- Upgrading openmrs-atomfeed version to 2.6.2-SNAPSHOT

BAH-1649 - | Rohit | - Upgrades openmrs atomfeed version to 2.6.2-SNAPSHOT

---

api/pom.xml

Adding dependency to solve the error of class not found exception

BAH-1256 | Adding javax.mail dependency

---

omod/src/main/resources/config.xml

Adding Author to Appointment Module

---

api/src/main/java/org/openmrs/module/appointments/notification/impl/DefaultMailSender.java
api/src/test/java/org/openmrs/module/appointments/notification/impl/DefaultMailSenderTest.java

This PR is about -
- Resolving mail sending issue for appointments
- Jira -> https://bahmni.atlassian.net/browse/BAH-2531

BAH-2531 - [ Rohit ] - Resolves mail sending issue for appointments

---

api/src/main/java/org/openmrs/module/appointments/notification/impl/DefaultMailSender.java

This PR is about:
- Adding check to send mail only if flag is true

BAH-2531 - [ Rohit ] - Adds check to send mail only if flag is true

---

api/pom.xml
api/src/main/java/org/openmrs/module/appointments/notification/impl/DefaultMailSender.java
api/src/main/java/org/openmrs/module/appointments/service/impl/TeleconsultationAppointmentService.java
api/src/test/java/org/openmrs/module/appointments/service/impl/TeleconsultationAppointmentServiceTest.java
omod/pom.xml
omod/src/main/resources/config.xml
pom.xml

This PR can be merged only when the tele-consultation [PR](https://github.com/Bahmni/openmrs-module-teleconsultation/pull/1) is merged

BAH-2410 | Integrating with tele-consultation module

---

api/src/main/java/org/openmrs/module/appointments/helper/AppointmentServiceHelper.java
api/src/main/java/org/openmrs/module/appointments/model/Appointment.java
api/src/main/java/org/openmrs/module/appointments/model/AppointmentPriority.java
api/src/main/java/org/openmrs/module/appointments/validator/impl/DefaultAppointmentValidator.java
api/src/main/java/org/openmrs/module/appointments/validator/impl/DefaultEditAppointmentValidator.java
api/src/main/resources/Appointment.hbm.xml
api/src/main/resources/liquibase.xml
api/src/test/java/org/openmrs/module/appointments/helper/AppointmentServiceHelperTest.java
api/src/test/java/org/openmrs/module/appointments/validator/impl/DefaultAppointmentValidatorTest.java
api/src/test/java/org/openmrs/module/appointments/validator/impl/DefaultEditAppointmentValidatorTest.java
omod/src/main/java/org/openmrs/module/appointments/web/contract/AppointmentDefaultResponse.java
omod/src/main/java/org/openmrs/module/appointments/web/contract/AppointmentRequest.java
omod/src/main/java/org/openmrs/module/appointments/web/mapper/AppointmentMapper.java
omod/src/test/java/org/openmrs/module/appointments/web/mapper/AppointmentMapperTest.java

New column in database for appointment priority. 
API able to save and return the priority

Kavitha, Umair | A-1204370983916597| add database column and api changes for priority

---

api/src/main/java/org/openmrs/module/appointments/validator/impl/DefaultAppointmentValidator.java
api/src/main/java/org/openmrs/module/appointments/validator/impl/DefaultEditAppointmentValidator.java
api/src/test/java/org/openmrs/module/appointments/validator/impl/DefaultAppointmentValidatorTest.java
api/src/test/java/org/openmrs/module/appointments/validator/impl/DefaultEditAppointmentValidatorTest.java
omod/src/main/java/org/openmrs/module/appointments/web/mapper/AppointmentMapper.java
omod/src/test/java/org/openmrs/module/appointments/web/mapper/AppointmentMapperTest.java

Removed Invalid priority types and related tests cases in a way the API will throw exception in case of invalid types being sent for priority

Kavitha | A-1204361352115416 | removed invalid priority and related tests

---

api/src/main/java/org/openmrs/module/appointments/helper/AppointmentServiceHelper.java
api/src/main/java/org/openmrs/module/appointments/model/AppointmentStatus.java

Card Ref : https://app.asana.com/0/1204322126657135/1204378118194874/f
Talk thread Ref : https://talk.openmrs.org/t/introducing-appointment-category-in-bahmni-appointments-module/39410

Kavitha | A-1204378118194874 | Allow dateless appointments if status is waitlist

---

api/src/main/java/org/openmrs/module/appointments/model/Appointment.java
omod/src/main/java/org/openmrs/module/appointments/web/contract/AppointmentDefaultResponse.java
omod/src/main/java/org/openmrs/module/appointments/web/mapper/AppointmentMapper.java

This PR has backend changes for showing the appointment creation date under awaiting appointments.
[Awaiting appointments UI changes](https://github.com/Bahmni/openmrs-module-appointments-frontend/pull/275) are made here.
[Asana card](https://app.asana.com/0/1204322126657135/1204378118194874)

Arjun | 1204378118194874 | Ability to view awaiting appointment List

---

omod/src/main/java/org/openmrs/module/appointments/web/mapper/AppointmentMapper.java
omod/src/test/java/org/openmrs/module/appointments/web/mapper/AppointmentMapperTest.java

Jira: https://bahmni.atlassian.net/browse/BAH-3210

BAH-3210 | Adds configAttributes to list view in appointment and awaiting appointment list

---

api/src/main/java/org/openmrs/module/appointments/events/eventListener/AppointmentSMSEventListener.java

- Small change to refactored method name to use Recurring appointment template instead of appointment booking sms template.

BAH-2962 | Refactored method name to recurringAppointment.

---

api/src/main/java/org/openmrs/module/appointments/dao/impl/AppointmentDaoImpl.java

Asana Link: https://app.asana.com/0/1204322126657135/1205878873908331/f
1) Add the order by date created asc
2) Set the max results limit to fetch from global property "webservices.rest.maxResultsDefault"

Add ordering and set max results

---

.github/workflows/build_publish.yaml
.github/workflows/release_deploy.yml
pom.xml

This PR adds a workflow which will perform a release deploy when a tag matching the version in pom.xml is pushed

BAH-4087 | Add. Workflow for release deploy

---

api/pom.xml
atom-feed/pom.xml
omod/pom.xml
pom.xml

This PR has commits for release of version 2.0.0 and also increments version to 2.1.0-SNAPSHOT

BAH-4087 | Release and increment dev version

---

api/pom.xml
atom-feed/pom.xml
omod/pom.xml
pom.xml

This PR has commits for release of 2.0.1 as a patch version for 2.0.0 as the release happened with SNAPSHOT builds.
Variables are extracted for the dependency versions

BAH-4087 | Release 2.0.1 patch for dependency version fixes
